In [127]:
import numpy as np # need to import these packages for functionality
import pandas as pd

df = pd.read_csv('Excel Proficiency Test - Ignite Visibility.csv') #importing csv file

df.info() #checking for any missing values and the type of objects

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2744 entries, 0 to 2743
Data columns (total 21 columns):
Reporting Starts              2744 non-null object
Reporting Ends                2744 non-null object
Ad Name                       2744 non-null object
Age                           2744 non-null object
Gender                        2744 non-null object
Campaign Name                 2744 non-null object
Ad Set Name                   2744 non-null object
Delivery                      2744 non-null object
Reach                         2744 non-null int64
Impressions                   2744 non-null int64
 Frequency                    2744 non-null object
All Clicks                    2744 non-null int64
All Click Through Rate        2744 non-null object
Link Clicks                   2744 non-null int64
Link Click Through Rate       2744 non-null object
Link Click Through Rate(%)    2744 non-null float64
Budget                        2744 non-null object
Budget Type                   2744 non-null object
Spend                         2744 non-null float64
Purchases                     122 non-null float64
Cost per Purchase             122 non-null float64
dtypes: float64(4), int64(4), object(13)
memory usage: 450.3+ KB

# Task 1: Gen>Age

1. Segment data by campaign name, gender, age
2. Show these columns: Frequency, Spend, Link Click Through Rate, Cost per Sale, Conversion Rate

## Notes on Task 1

- I created a new variable called "Frequency as Num Type." First, I replaced the cells called "#DIV/0!" to zero (0) and converted the values into a numerical type (float) so that we can calculate the average for each column. 

- 'Conversion Rate' was a new column that I made by doing Purchases/Clicks

- Since the image of the pivot table gets cut off cus there are too many columns, one way to see the pivot table is to do: df.loc[''] and inside the brackets you can put the name of each campaign for example to identify info per campaign

In [129]:
## create pivot table

df['Frequency as Num Type'] = df[' Frequency '].replace('#DIV/0!', 0).astype(float)

df['Conversion Rate'] = df['Purchases']/df['All Clicks']

pd.pivot_table(df, index=['Campaign Name','Gender','Age'], 
               values=['Frequency as Num Type','Spend', 'Link Click Through Rate(%)',
                      'Cost per Purchase','Conversion Rate'])

                                                    Conversion Rate  \
Campaign Name                        Gender  Age
Ignite | Prospecting | Africa (Misc) female  18-24         0.111111
                                             25-34         0.133333
                                             35-44         0.350000
                                             45-54         0.611111
                                             55-64              NaN
                                     male    18-24              NaN
                                             25-34         0.219828
                                             35-44         0.340618
                                             45-54         0.166667
                                             55-64              NaN
                                     unknown 18-24              NaN
                                             25-34              NaN
                                             35-44              NaN
                                             45-54              NaN
                                             55-64              NaN
Ignite | Prospecting | Asia (Poor)   female  18-24              NaN
                                             25-34              NaN
                                             35-44              NaN
                                             45-54         0.066667
                                             55-64              NaN
                                             65+                NaN
                                     male    18-24              NaN
                                             25-34         0.005102
                                             35-44         0.102083
                                             45-54         0.050360
                                             55-64         0.291667
                                             65+                NaN
                                     unknown 18-24              NaN
                                             25-34              NaN
                                             35-44              NaN
...                                                             ...
Ignite | Prospecting | North America female  18-24         0.250000
                                             25-34         0.169643
                                             35-44         0.068966
                                             45-54              inf
                                             55-64              NaN
                                             65+                NaN
                                     male    18-24              inf
                                             25-34              inf
                                             35-44         0.176250
                                             45-54         0.273810
                                             55-64              NaN
                                             65+                NaN
                                     unknown 18-24              NaN
                                             25-34              NaN
                                             35-44              NaN
                                             45-54              NaN
                                             55-64              NaN
                                             65+                NaN
Ignite | Prospecting | UK            female  18-24              NaN
                                             25-34         0.187500
                                             35-44         0.268966
                                             45-54         0.268421
                                     male    18-24              NaN
                                             25-34         0.138462
                                             35-44         0.171429
                                             45-54         0.075000
                                     unknown 18-24              NaN
                                             25-34              NaN
                                             35-44              NaN
                                             45-54              NaN

                                                    Cost per Purchase  \
Campaign Name                        Gender  Age
Ignite | Prospecting | Africa (Misc) female  18-24           0.550000
                                             25-34           1.800000
                                             35-44           1.417500
                                             45-54           1.243333
                                             55-64                NaN
                                     male    18-24                NaN
                                             25-34           3.080000
                                             35-44           1.663000
                                             45-54           3.350000
                                             55-64                NaN
                                     unknown 18-24                NaN
                                             25-34                NaN
                                             35-44                NaN
                                             45-54                NaN
                                             55-64                NaN
Ignite | Prospecting | Asia (Poor)   female  18-24                NaN
                                             25-34                NaN
                                             35-44                NaN
                                             45-54           2.005000
                                             55-64                NaN
                                             65+                  NaN
                                     male    18-24                NaN
                                             25-34          19.740000
                                             35-44           1.593333
                                             45-54           4.461917
                                             55-64           0.252500
                                             65+                  NaN
                                     unknown 18-24                NaN
                                             25-34                NaN
                                             35-44                NaN
...                                                               ...
Ignite | Prospecting | North America female  18-24           6.860000
                                             25-34          23.779566
                                             35-44          22.179144
                                             45-54          10.979769
                                             55-64                NaN
                                             65+                  NaN
                                     male    18-24           2.110000
                                             25-34          10.730000
                                             35-44          14.071082
                                             45-54          16.874507
                                             55-64                NaN
                                             65+                  NaN
                                     unknown 18-24                NaN
                                             25-34                NaN
                                             35-44                NaN
                                             45-54                NaN
                                             55-64                NaN
                                             65+                  NaN
Ignite | Prospecting | UK            female  18-24                NaN
                                             25-34          10.273333
                                             35-44           5.765000
                                             45-54           5.505000
                                     male    18-24                NaN
                                             25-34          19.640000
                                             35-44           8.536666
                                             45-54          14.947500
                                     unknown 18-24                NaN
                                             25-34                NaN
                                             35-44                NaN
                                             45-54                NaN

                                                    Frequency as Num Type  \
Campaign Name                        Gender  Age
Ignite | Prospecting | Africa (Misc) female  18-24               1.555000
                                             25-34               1.625758
                                             35-44               1.670000
                                             45-54               1.441563
                                             55-64               1.391429
                                     male    18-24               1.666333
                                             25-34               1.797879
                                             35-44               1.672000
                                             45-54               1.486667
                                             55-64               1.418000
                                     unknown 18-24               1.125000
                                             25-34               1.610909
                                             35-44               1.643846
                                             45-54               1.385238
                                             55-64               2.100000
Ignite | Prospecting | Asia (Poor)   female  18-24               1.690000
                                             25-34               1.470000
                                             35-44               1.527222
                                             45-54               1.400556
                                             55-64               1.495556
                                             65+                 1.455000
                                     male    18-24               1.390000
                                             25-34               1.310000
                                             35-44               1.470000
                                             45-54               1.488889
                                             55-64               1.488333
                                             65+                 1.615000
                                     unknown 18-24               1.000000
                                             25-34               1.525000
                                             35-44               1.320556
...                                                                   ...
Ignite | Prospecting | North America female  18-24               1.389500
                                             25-34               1.338000
                                             35-44               1.335250
                                             45-54               1.360500
                                             55-64               1.423750
                                             65+                 1.906667
                                     male    18-24               1.314250
                                             25-34               1.316000
                                             35-44               1.284000
                                             45-54               1.269000
                                             55-64               1.325417
                                             65+                 1.596667
                                     unknown 18-24               1.469744
                                             25-34               1.322000
                                             35-44               1.281500
                                             45-54               1.344324
                                             55-64               1.162353
                                             65+                 1.826667
Ignite | Prospecting | UK            female  18-24               1.455556
                                             25-34               1.500000
                                             35-44               1.561111
                                             45-54               1.828889
                                     male    18-24               1.505556
                                             25-34               1.420000
                                             35-44               1.422222
                                             45-54               1.530000
                                     unknown 18-24               2.875714
                                             25-34               1.304444
                                             35-44               1.453333
                                             45-54               1.557500

                                                    Link Click Through Rate(%)  \
Campaign Name                        Gender  Age
Ignite | Prospecting | Africa (Misc) female  18-24                    0.200940
                                             25-34                    0.182924
                                             35-44                    0.192394
                                             45-54                    0.242038
                                             55-64                    0.000000
                                     male    18-24                    0.163177
                                             25-34                    0.264742
                                             35-44                    0.256000
                                             45-54                    0.129736
                                             55-64                    0.000000
                                     unknown 18-24                    0.000000
                                             25-34                    0.000000
                                             35-44                    0.311677
                                             45-54                    0.595238
                                             55-64                    0.000000
Ignite | Prospecting | Asia (Poor)   female  18-24                    0.378500
                                             25-34                    0.168800
                                             35-44                    0.163344
                                             45-54                    0.290628
                                             55-64                    0.235533
                                             65+                      0.060600
                                     male    18-24                    0.057367
                                             25-34                    0.115425
                                             35-44                    0.205706
                                             45-54                    0.213867
                                             55-64                    0.243000
                                             65+                      0.345250
                                     unknown 18-24                    0.000000
                                             25-34                    0.609750
                                             35-44                    0.168350
...                                                                        ...
Ignite | Prospecting | North America female  18-24                    0.168792
                                             25-34                    0.072868
                                             35-44                    0.118815
                                             45-54                    0.181222
                                             55-64                    0.157238
                                             65+                      0.561333
                                     male    18-24                    0.103402
                                             25-34                    0.219370
                                             35-44                    0.260145
                                             45-54                    0.121143
                                             55-64                    0.024800
                                             65+                      0.238100
                                     unknown 18-24                    0.021731
                                             25-34                    0.027778
                                             35-44                    0.047170
                                             45-54                    0.054054
                                             55-64                    0.367647
                                             65+                      0.000000
Ignite | Prospecting | UK            female  18-24                    0.115744
                                             25-34                    0.094478
                                             35-44                    0.105833
                                             45-54                    0.229644
                                     male    18-24                    0.213744
                                             25-34                    0.100389
                                             35-44                    0.240978
                                             45-54                    0.223678
                                     unknown 18-24                    0.000000
                                             25-34                    0.000000
                                             35-44                    0.000000
                                             45-54                    0.090575

                                                        Spend
Campaign Name                        Gender  Age
Ignite | Prospecting | Africa (Misc) female  18-24   0.261667
                                             25-34   0.799394
                                             35-44   0.763125
                                             45-54   0.570625
                                             55-64   0.044643
                                     male    18-24   0.381667
                                             25-34   1.055455
                                             35-44   0.797429
                                             45-54   0.482727
                                             55-64   0.021200
                                     unknown 18-24   0.003750
                                             25-34   0.011364
                                             35-44   0.026154
                                             45-54   0.030000
                                             55-64   0.003000
Ignite | Prospecting | Asia (Poor)   female  18-24   0.535000
                                             25-34   1.533333
                                             35-44   0.600556
                                             45-54   5.112778
                                             55-64   0.339444
                                             65+     0.195000
                                     male    18-24   2.423333
                                             25-34   5.277500
                                             35-44   1.538889
                                             45-54   8.271667
                                             55-64   0.511667

# Task 2: Unique Sort 

1. Include the same columns as above
2. Identify which two campaigns have the highest link click through rate
3. Utilize filters to only show these two campaigns
4. Segment data to show: campaign name, ad set name, and ad names that belong to these two campaigns

## Notes on Task 2

- To simplify identify which two campaigns have the highest click through rate, I made the simple pivot table called 'task 2'
- After inspection, I identified that 'Ignite | Prospecting | Canada' and 'Ignite | Prospecting | LATAM' have the highest link click through rate
- 'unique_sort' and 'unique_sort_finalQs' are pivot tables i made for #4 and #3 of the assignment, respectively.

In [58]:
task_2 = pd.pivot_table(df, index=['Campaign Name'], 
               values=['Link Click Through Rate'])
task_2

                                      Link Click Through Rate
Campaign Name
Ignite | Prospecting | Africa (Misc)                 0.184531
Ignite | Prospecting | Asia (Poor)                   0.186428
Ignite | Prospecting | Asia (Rich)                   0.173654
Ignite | Prospecting | Australia                     0.323287
Ignite | Prospecting | Canada                        0.674750
Ignite | Prospecting | Europe (Poor)                 0.187760
Ignite | Prospecting | Europe (Rich)                 0.280136
Ignite | Prospecting | LATAM                         0.809461
Ignite | Prospecting | Middle East                   0.288183
Ignite | Prospecting | North America                 0.124896
Ignite | Prospecting | UK                            0.120429

In [59]:
unique_sort = pd.pivot_table(df, index=['Campaign Name','Ad Set Name','Ad Name'], 
               values=['Frequency as Num Type','Spend', 'Link Click Through Rate',
                      'Cost per Purchase','Conversion Rate'])

unique_sort.loc[['Ignite | Prospecting | Canada', 'Ignite | Prospecting | LATAM']]

                                                                                                                     Conversion Rate  \
Campaign Name                 Ad Set Name                                        Ad Name
Ignite | Prospecting | Canada [CA] Lookalike (CA, 1%) - Control Panel Visitors   Desktop Carousel (Short Headline)          0.174892
                              [CA] Podcast_Lookalike (CA, 1%) - Control Panel... Blog: Selling on Amazon (Podcast)               NaN
Ignite | Prospecting | LATAM  Lookalike (LATAM, 1%) Direct Paid                  Blog Post: Spanish Cart Abandon            0.117647
                                                                                 Blog Post: Spanish SWOT                    0.034223
                                                                                 Blog Post: Spanish YouTube Promote         0.024349
                                                                                 Blue Shirt Box Man - Relaxed (SP)          0.041595
                                                                                 Easy Use Woman - Desk (SP)                 0.046929
                                                                                 Easy Use Woman - Smile First (SP)               NaN

                                                                                                                     Cost per Purchase  \
Campaign Name                 Ad Set Name                                        Ad Name
Ignite | Prospecting | Canada [CA] Lookalike (CA, 1%) - Control Panel Visitors   Desktop Carousel (Short Headline)           14.650753
                              [CA] Podcast_Lookalike (CA, 1%) - Control Panel... Blog: Selling on Amazon (Podcast)                 NaN
Ignite | Prospecting | LATAM  Lookalike (LATAM, 1%) Direct Paid                  Blog Post: Spanish Cart Abandon              1.379544
                                                                                 Blog Post: Spanish SWOT                     11.856667
                                                                                 Blog Post: Spanish YouTube Promote           9.074667
                                                                                 Blue Shirt Box Man - Relaxed (SP)            6.085000
                                                                                 Easy Use Woman - Desk (SP)                   3.104000
                                                                                 Easy Use Woman - Smile First (SP)                 NaN

                                                                                                                     Frequency as Num Type  \
Campaign Name                 Ad Set Name                                        Ad Name
Ignite | Prospecting | Canada [CA] Lookalike (CA, 1%) - Control Panel Visitors   Desktop Carousel (Short Headline)                1.678889
                              [CA] Podcast_Lookalike (CA, 1%) - Control Panel... Blog: Selling on Amazon (Podcast)                1.864444
Ignite | Prospecting | LATAM  Lookalike (LATAM, 1%) Direct Paid                  Blog Post: Spanish Cart Abandon                  1.550833
                                                                                 Blog Post: Spanish SWOT                          1.462500
                                                                                 Blog Post: Spanish YouTube Promote               1.642500
                                                                                 Blue Shirt Box Man - Relaxed (SP)                1.673333
                                                                                 Easy Use Woman - Desk (SP)                       1.793333
                                                                                 Easy Use Woman - Smile First (SP)                1.401667

                                                                                                                     Link Click Through Rate  \
Campaign Name                 Ad Set Name                                        Ad Name
Ignite | Prospecting | Canada [CA] Lookalike (CA, 1%) - Control Panel Visitors   Desktop Carousel (Short Headline)                  0.366761
                              [CA] Podcast_Lookalike (CA, 1%) - Control Panel... Blog: Selling on Amazon (Podcast)                  0.982739
Ignite | Prospecting | LATAM  Lookalike (LATAM, 1%) Direct Paid                  Blog Post: Spanish Cart Abandon                    0.307017
                                                                                 Blog Post: Spanish SWOT                            1.071500
                                                                                 Blog Post: Spanish YouTube Promote                 1.123692
                                                                                 Blue Shirt Box Man - Relaxed (SP)                  0.603458
                                                                                 Easy Use Woman - Desk (SP)                         1.389125
                                                                                 Easy Use Woman - Smile First (SP)                  0.361975

                                                                                                                         Spend
Campaign Name                 Ad Set Name                                        Ad Name
Ignite | Prospecting | Canada [CA] Lookalike (CA, 1%) - Control Panel Visitors   Desktop Carousel (Short Headline)    8.912222
                              [CA] Podcast_Lookalike (CA, 1%) - Control Panel... Blog: Selling on Amazon (Podcast)    2.670556
Ignite | Prospecting | LATAM  Lookalike (LATAM, 1%) Direct Paid                  Blog Post: Spanish Cart Abandon      2.520833
                                                                                 Blog Post: Spanish SWOT              6.719167
                                                                                 Blog Post: Spanish YouTube Promote  14.203333
                                                                                 Blue Shirt Box Man - Relaxed (SP)    4.715000
                                                                                 Easy Use Woman - Desk (SP)           2.701667
                                                                                 Easy Use Woman - Smile First (SP)    1.656667

In [61]:
unique_sort_finalQs = pd.pivot_table(df, index=['Campaign Name','Gender','Age'], 
               values=['Frequency as Num Type','Spend', 'Link Click Through Rate',
                      'Cost per Purchase','Conversion Rate'])

unique_sort_finalQs.loc[['Ignite | Prospecting | Canada', 'Ignite | Prospecting | LATAM']]

                                             Conversion Rate  \
Campaign Name                 Gender  Age
Ignite | Prospecting | Canada female  18-24              NaN
                                      25-34         0.181818
                                      35-44         0.200000
                                      45-54              NaN
                                      55-64              NaN
                                      65+                NaN
                              male    18-24              NaN
                                      25-34              NaN
                                      35-44              NaN
                                      45-54         0.142857
                                      55-64              NaN
                                      65+                NaN
                              unknown 18-24              NaN
                                      25-34              NaN
                                      35-44              NaN
                                      45-54              NaN
                                      55-64              NaN
                                      65+                NaN
Ignite | Prospecting | LATAM  female  18-24              NaN
                                      25-34         0.074074
                                      35-44              NaN
                                      45-54         0.057593
                              male    18-24         0.068439
                                      25-34         0.015653
                                      35-44         0.024717
                                      45-54         0.051937
                              unknown 18-24              NaN
                                      25-34              NaN
                                      35-44              NaN
                                      45-54              NaN

                                             Cost per Purchase  \
Campaign Name                 Gender  Age
Ignite | Prospecting | Canada female  18-24                NaN
                                      25-34          12.954192
                                      35-44          20.098747
                                      45-54                NaN
                                      55-64                NaN
                                      65+                  NaN
                              male    18-24                NaN
                                      25-34                NaN
                                      35-44                NaN
                                      45-54          10.899321
                                      55-64                NaN
                                      65+                  NaN
                              unknown 18-24                NaN
                                      25-34                NaN
                                      35-44                NaN
                                      45-54                NaN
                                      55-64                NaN
                                      65+                  NaN
Ignite | Prospecting | LATAM  female  18-24                NaN
                                      25-34           2.530000
                                      35-44                NaN
                                      45-54           4.390000
                              male    18-24           2.699772
                                      25-34          11.557917
                                      35-44          10.695000
                                      45-54           3.713417
                              unknown 18-24                NaN
                                      25-34                NaN
                                      35-44                NaN
                                      45-54                NaN

                                             Frequency as Num Type  \
Campaign Name                 Gender  Age
Ignite | Prospecting | Canada female  18-24               2.115000
                                      25-34               1.730000
                                      35-44               1.760000
                                      45-54               1.750000
                                      55-64               2.155000
                                      65+                 2.410000
                              male    18-24               1.625000
                                      25-34               1.750000
                                      35-44               1.540000
                                      45-54               1.565000
                                      55-64               1.970000
                                      65+                 1.695000
                              unknown 18-24               1.580000
                                      25-34               1.805000
                                      35-44               1.465000
                                      45-54               1.765000
                                      55-64               1.380000
                                      65+                 1.830000
Ignite | Prospecting | LATAM  female  18-24               1.585000
                                      25-34               1.490000
                                      35-44               1.486667
                                      45-54               1.560000
                              male    18-24               1.580000
                                      25-34               1.496667
                                      35-44               1.573333
                                      45-54               1.540000
                              unknown 18-24               2.058333
                                      25-34               1.391667
                                      35-44               1.560000
                                      45-54               1.726667

                                             Link Click Through Rate  \
Campaign Name                 Gender  Age
Ignite | Prospecting | Canada female  18-24                 0.154000
                                      25-34                 0.194600
                                      35-44                 0.304250
                                      45-54                 0.352450
                                      55-64                 1.188100
                                      65+                   1.267600
                              male    18-24                 0.255050
                                      25-34                 0.069650
                                      35-44                 0.447750
                                      45-54                 0.223200
                                      55-64                 0.485450
                                      65+                   0.159750
                              unknown 18-24                 6.250000
                                      25-34                 0.000000
                                      35-44                 0.000000
                                      45-54                 0.000000
                                      55-64                 0.793650
                                      65+                   0.000000
Ignite | Prospecting | LATAM  female  18-24                 0.408017
                                      25-34                 0.649483
                                      35-44                 0.805367
                                      45-54                 0.917633
                              male    18-24                 0.618483
                                      25-34                 0.819150
                                      35-44                 0.838467
                                      45-54                 1.106217
                              unknown 18-24                 0.574717
                                      25-34                 1.000817
                                      35-44                 1.110767
                                      45-54                 0.864417

                                                 Spend
Campaign Name                 Gender  Age
Ignite | Prospecting | Canada female  18-24   4.859779
                                      25-34  16.409192
                                      35-44  13.514373
                                      45-54   7.649638
                                      55-64   3.294822
                                      65+     2.284906
                              male    18-24   9.449555
                                      25-34  17.719176
                                      35-44  14.179289
                                      45-54   6.799660
                                      55-64   2.684875
                                      65+     2.074895
                              unknown 18-24   0.199989
                                      25-34   1.114943
                                      35-44   0.659969
                                      45-54   0.859960
                                      55-64   0.249988
                                      65+     0.239991
Ignite | Prospecting | LATAM  female  18-24   1.619940
                                      25-34   6.363105
                                      35-44   5.781465
                                      45-54   2.921570
                              male    18-24   5.881515
                                      25-34  18.031266
                                      35-44  15.549649
                                      45-54   7.723176
                              unknown 18-24   0.023331
                                      25-34   0.276661
                                      35-44   0.549992
                                      45-54   0.311663

# Final Questions

#### 1. What was the ad name that spent the most within the campaign with the highest link click through rate?
Blog Post: Spanish YouTube Promote	

#### 2. Which 2 campaigns had the highest conversion rate? Which 3 ad groups withn each campaign have the highest conversion rate?
- Ignite | Prospecting | Europe (Rich) and Ignite | Prospecting | Asia (Rich)

In [133]:
finalQ_2 = pd.pivot_table(df, index=['Campaign Name'], 
               values=['Conversion Rate'])
finalQ_2 # Ignite | Prospecting | Europe (Rich)	 and Ignite | Prospecting | Asia (Rich)

                                      Conversion Rate
Campaign Name
Ignite | Prospecting | Africa (Misc)         0.320021
Ignite | Prospecting | Asia (Poor)           0.094469
Ignite | Prospecting | Asia (Rich)           0.424522
Ignite | Prospecting | Australia             0.136327
Ignite | Prospecting | Canada                0.174892
Ignite | Prospecting | Europe (Poor)         0.285913
Ignite | Prospecting | Europe (Rich)         0.550000
Ignite | Prospecting | LATAM                 0.041831
Ignite | Prospecting | Middle East           0.025127
Ignite | Prospecting | North America              inf
Ignite | Prospecting | UK                    0.191706

In [134]:
finalQ_2_1 = pd.pivot_table(df, index=['Campaign Name','Ad Set Name'], 
               values=['Conversion Rate'])

finalQ_2_1.loc[['Ignite | Prospecting | Europe (Rich)','Ignite | Prospecting | Asia (Rich)']]

                                                                                    Conversion Rate
Campaign Name                        Ad Set Name
Ignite | Prospecting | Asia (Rich)   [Asia - rich] Lookalke 1% - Extra Countries           1.125000
                                     [Asia - rich] Podcast_Boosted Posts                   0.021277
                                     [Asia - rich] eCommerce & Site Builders - 44+         0.258237
Ignite | Prospecting | Europe (Rich) [EU - rich] Lookalke 1% - Extra Countries             0.666667
                                     [EU - rich] eCommerce & Site Builders - 44+           0.200000